name: Build and Push Docker Image

on:
    push: null

env:
    REGISTRY: ghcr.io
    NAMESPACE_AND_IMAGE_NAME: ${{ github.repository }}
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: docker/setup-buildx-action@v2
            - uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
            - uses: docker/build-push-action@v4
              with:
                  push: ${{ env.BRANCH_NAME == github.event.repository.default_branch }}
                  tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE_AND_IMAGE_NAME }}:${{ env.VERSION }}

            - run: echo ${{ steps.docker_build.outputs.digest }}
